services:
  database:
    image: postgres:17.5-alpine3.21
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
